name: Text to Speech Using GUI

#we are pushing on main branch.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

##giving to the permission of Github action
permissions:
  contents: read

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix: #Project buield karna hai python 3.11 verion sysyem mein
        os: [window-latest] #operating system ke liye comfortable hai 
        python-version: [ "3.9" ] ## which version you used to create python project      

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}    
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run:
        pip install -r requirements.txt

